### ISSUE TITLE
interfere with default panel escaping.

### ISSUE THREAD

**Issue by ctf0** [glutanimate/sublime-deselect#1]
this is a must have plugin ,which am thankful for
i found a couple of prob so far which are
- if the search_panel was open pressing escape wont hide it
- auto_complete panel cant be hided/canceled

i know i can add another key bind for the plugin ,but it would be much better if one keystroke can do everything as intended.

**Comment by glutanimate** [comment]
Thanks for your feedback!

I think I might know what's going on: Did you by any chance modify the default key binding or define it yourself in your Sublime Text configuration? I forgot to add the `context` value to the key binding example in the README, so if you used that one it would explain why the plugin was interfering with other ST functions. The README should include the correct key binding now (1db21a1b57af8a4ab191a2913b1b50b8ec208db9).

With the `context` in place, the behaviour is as follows:
- text selected? → first `Esc`: deselect text
- panel active? → first `Esc`: hide panel
- text selected + panel active → first `Esc`: deselect text; second `Esc`: hide panel

**Comment by ctf0** [comment]
much better now ,thanx.
